# Generated by Django 5.0.4 on 2024-05-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='test',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='condition_text',
        ),
        migrations.AddField(
            model_name='question',
            name='answer_options',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='type_answer',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
