# Generated by Django 5.0.4 on 2024-05-16 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0002_remove_question_test_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='condition_text',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('is_correct', models.BooleanField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.question')),
            ],
        ),
    ]
